import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import Replicate from "replicate";

// ─── Rate Limiting (in-memory, IP-based) ────────────────────────────
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();
const RATE_LIMIT_WINDOW = 60_000; // 1 minute
const RATE_LIMIT_MAX = 10; // max requests per window

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW });
    return true;
  }

  if (entry.count >= RATE_LIMIT_MAX) {
    return false;
  }

  entry.count++;
  return true;
}

// ─── Prompt Engineering ──────────────────────────────────────────────
//
// STEP 1 ONLY — finish room surfaces (walls, floor, ceiling, lighting).
// No furniture. Transform a construction-site photo into a clean,
// finished empty room while preserving geometry + camera angle.

function buildResponsesPrompt(stylePrompt: string): string {
  return [
    "Edit this photo of a room under construction.",
    "Keep the exact same camera angle, perspective, and room shape.",
    "Replace the raw concrete floor with a polished finished floor.",
    "Replace raw plaster walls with smooth painted walls. Add baseboards.",
    "Replace the unfinished ceiling with a clean painted ceiling.",
    "Remove all exposed wires, dangling cables, and junction boxes.",
    "Add one elegant ceiling light fixture where wires hang.",
    "Add finished covers on all electrical outlets.",
    "Keep the room completely empty — no furniture, no decoration.",
    `Color palette: ${stylePrompt}.`,
  ].join(" ");
}

function buildFluxPrompt(stylePrompt: string): string {
  return [
    `Beautifully finished empty room, ${stylePrompt} color palette.`,
    "Smooth painted walls with baseboards, polished floor, clean painted ceiling, elegant ceiling light fixture, finished outlet covers.",
    "No exposed wires, no raw concrete, no construction debris.",
    "Completely empty — no furniture, no rugs, no decoration, no objects.",
    "Interior architecture photograph, DSLR 16-35mm f/8, deep depth of field, sharp focus, natural lighting.",
  ].join(" ");
}

// ─── OpenAI Responses API (PRIMARY) ─────────────────────────────────
//
// Uses the Responses API with the image_generation tool.
// The model SEES the image via vision and generates an edited version.
// input_fidelity: "high" preserves geometry, lighting, and perspective.
// This is fundamentally different from images.edit (inpainting).
async function tryOpenAIResponses(
  imageBase64: string,
  stylePrompt: string
): Promise<{ image: string; model: string }> {
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  const prompt = buildResponsesPrompt(stylePrompt);

  const response = await openai.responses.create({
    model: "gpt-4.1",
    input: [
      {
        role: "user",
        content: [
          {
            type: "input_image",
            image_url: `data:image/jpeg;base64,${imageBase64}`,
            detail: "high",
          },
          {
            type: "input_text",
            text: prompt,
          },
        ],
      },
    ],
    tools: [
      {
        type: "image_generation",
        input_fidelity: "high",
      },
    ],
  });

  // Extract the generated image from response output
  const imageOutput = response.output.find(
    (o: { type: string }) => o.type === "image_generation_call"
  );

  if (!imageOutput || !("result" in imageOutput)) {
    throw new Error("No image generated by OpenAI Responses API");
  }

  const resultB64 = (imageOutput as { result: string }).result;
  if (!resultB64) {
    throw new Error("Empty image result from OpenAI Responses API");
  }

  return {
    image: `data:image/png;base64,${resultB64}`,
    model: "OpenAI GPT-4.1 (Responses API)",
  };
}

// ─── Replicate Fallback (Flux Depth Pro) ─────────────────────────────
//
// Flux Depth Pro extracts a depth map from the input image and uses it
// to constrain generation. This preserves the 3D spatial structure
// (walls, floor, ceiling, windows) while allowing surface restyling.
async function tryFluxDepth(
  imageBase64: string,
  stylePrompt: string
): Promise<{ image: string; model: string }> {
  const replicate = new Replicate({ auth: process.env.REPLICATE_API_TOKEN });

  const dataUri = `data:image/jpeg;base64,${imageBase64}`;

  const output = await replicate.run(
    "black-forest-labs/flux-depth-pro" as `${string}/${string}`,
    {
      input: {
        prompt: buildFluxPrompt(stylePrompt),
        control_image: dataUri,
        steps: 25,
        guidance: 30,
        output_format: "png",
      },
    }
  );

  // Flux Depth Pro returns a FileOutput or URL string
  let imageUrl: string;
  if (typeof output === "string") {
    imageUrl = output;
  } else if (output && typeof output === "object" && "url" in output) {
    imageUrl = (output as { url: () => string }).url();
  } else if (Array.isArray(output) && output.length > 0) {
    imageUrl = typeof output[0] === "string" ? output[0] : String(output[0]);
  } else {
    throw new Error("Unexpected output format from Flux Depth Pro");
  }

  const imageResponse = await fetch(imageUrl);
  const arrayBuffer = await imageResponse.arrayBuffer();
  const base64 = Buffer.from(arrayBuffer).toString("base64");

  return {
    image: `data:image/webp;base64,${base64}`,
    model: "Flux Depth Pro",
  };
}

// ─── API Route Handler ──────────────────────────────────────────────
export async function POST(request: NextRequest) {
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "unknown";

  if (!checkRateLimit(ip)) {
    return NextResponse.json(
      { error: "Trop de requêtes. Veuillez patienter une minute avant de réessayer." },
      { status: 429 }
    );
  }

  try {
    const body = await request.json();
    const { image, stylePrompt } = body as {
      image: string;
      stylePrompt: string;
    };

    if (!image || !stylePrompt || !stylePrompt.trim()) {
      return NextResponse.json(
        { error: "Image et style requis" },
        { status: 400 }
      );
    }

    const base64Image = image.replace(/^data:image\/[\w+]+;base64,/, "");

    const estimatedSize = (base64Image.length * 3) / 4;
    if (estimatedSize > 10 * 1024 * 1024) {
      return NextResponse.json(
        { error: "L'image dépasse la taille maximale de 10 Mo" },
        { status: 413 }
      );
    }

    // Priority 1: OpenAI Responses API (vision + image generation)
    // Priority 2: Flux Depth Pro on Replicate (depth-map structural preservation)
    let openaiError: Error | null = null;
    let replicateError: Error | null = null;

    if (process.env.OPENAI_API_KEY) {
      try {
        const result = await tryOpenAIResponses(base64Image, stylePrompt.trim());
        return NextResponse.json(result);
      } catch (err) {
        openaiError = err instanceof Error ? err : new Error(String(err));
        console.error("OpenAI Responses API failed:", openaiError.message);
      }
    }

    if (process.env.REPLICATE_API_TOKEN) {
      try {
        const result = await tryFluxDepth(base64Image, stylePrompt.trim());
        return NextResponse.json(result);
      } catch (err) {
        replicateError = err instanceof Error ? err : new Error(String(err));
        console.error("Flux Depth Pro also failed:", replicateError.message);
      }
    }

    if (!process.env.OPENAI_API_KEY && !process.env.REPLICATE_API_TOKEN) {
      return NextResponse.json(
        { error: "Aucune clé API configurée. Veuillez configurer OPENAI_API_KEY ou REPLICATE_API_TOKEN." },
        { status: 500 }
      );
    }

    const details: string[] = [];
    if (openaiError) details.push(`OpenAI : ${openaiError.message}`);
    if (replicateError) details.push(`Replicate : ${replicateError.message}`);

    return NextResponse.json(
      { error: `Échec de la génération. ${details.join(" | ")}` },
      { status: 503 }
    );
  } catch (error) {
    console.error("Generation error:", error);
    return NextResponse.json(
      { error: "Erreur interne du serveur" },
      { status: 500 }
    );
  }
}
